steps:
# Build and push the base image
- name: 'gcr.io/${_PROJECT_ID}/my-docker-repo/gcp-terraform-build:latest'
  id: build
  args: [
    'docker',
    'build',
    '-t', '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/${_IMAGE_NAME}:latest',
    '-f', 'Dockerfile',
    '.'
  ]

- name: 'gcr.io/${_PROJECT_ID}/my-docker-repo/gcp-terraform-build:latest'
  id: push
  args: ['docker', 'push', '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/${_IMAGE_NAME}:latest']
  waitFor: ['build']

images:
- '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/${_IMAGE_NAME}:latest'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _LOCATION: 'europe-west1'
  _PROJECT_ID: '${PROJECT_ID}'
  _REPOSITORY_ID: 'my-docker-repo'
  _IMAGE_NAME: 'base-image'