steps:
# Build and push the base image
- name: 'gcr.io/cloud-builders/docker'
  id: build
  args: [
    'build',
    '-t', '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/${_IMAGE_NAME}:latest',
    '-f', 'Dockerfile',
    '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: push
  args: ['push', '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/${_IMAGE_NAME}:latest']
  waitFor: ['build']

images:
- '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/${_IMAGE_NAME}:latest'
