steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/base-image:${_TAG}',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/base-image:${_TAG}']
images:
- '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_ID}/base-image:${_TAG}'
options:
  logging: CLOUD_LOGGING_ONLY